### ISSUE TITLE
The plugin is not showing up in HDT.

### ISSUE THREAD

**Issue by Tenebranas** [stdscatchemall/HDTCompatabilityWindow#5]
So, Win 7, I have had a clean install, and then put the files from the archive in the Plugins folder, but HDTCompWindow is not showing up. See for yourself. (OBS)
![8fea4f4ed7](https://cloud.githubusercontent.com/assets/13907081/9414696/1eb74248-4843-11e5-813d-0728cb747a37.jpg)
![3c7dd41785](https://cloud.githubusercontent.com/assets/13907081/9414698/22955dd2-4843-11e5-8ff5-940cf780818b.jpg)
I have enabled them in properties. Halp pls.

**Comment by stdscatchemall** [comment]
Issue fixed with release just pushed now. The plugin actually exists, just not in the normal window. Please update and enjoy :)
