### ISSUE TITLE
Well, again.

### ISSUE THREAD

**Issue by Tenebranas** [stdscatchemall/HDTCompatabilityWindow#6]
I dunno if I am retarded, or there is some other problem, but even after the update, i still can't see it in HDT, and there is no other window in OBS. 

OBS screenshot:
![c8f4a2ea02](https://cloud.githubusercontent.com/assets/13907081/9415052/54cc9638-4845-11e5-8cd8-458842fcd5cd.jpg)

**Comment by stdscatchemall** [comment]
There is a new setting that you might have disabled causing it to not appear when HS isn't in foreground. Can you send me a screenshot of your settings please?

**Comment by stdscatchemall** [comment]
Since I haven't heard back from you, I will be closing this issue. Feel free to re-open if you are still requiring help!
