### ISSUE TITLE
Next HDT Update

### ISSUE THREAD

**Issue by Epix37** [stdscatchemall/HDTCompatabilityWindow#7]
The next HDT update will most likely require some (minor) changes for your plugin to properly work.

See here for more info and a pre-release download: https://github.com/Epix37/HDT-Test/releases/tag/v0.10.12PRE3

**Comment by Epix37** [comment]
Fixed a problem where the GameV2 instance was not accessible, please download the latest pre-release here: https://github.com/Epix37/HDT-Test/releases

**Note:** You plugin will no doubt still "run" with this version but `Hearthstone.Game.cs` **is no longer used** and any references to it need to be changed to `API.Core.Game`.

**Comment by stdscatchemall** [comment]
Plugin Updated to work with latest version according to GitHub source!

**Comment by Epix37** [comment]
The update is not live yet! I'm gonna guess the new version does not work with v0.10.11.

**Comment by Epix37** [comment]
If I find no more major problems the update should go out [11am UTC](http://everytimezone.com/#2015-8-24,-60,cn3).

**Comment by stdscatchemall** [comment]
Alright, ill take the release down for now. xD Put it back up once it's released.
