### ISSUE TITLE
HDT Compatibility Window not displaying correctly

### ISSUE THREAD

**Issue by Assmodius** [stdscatchemall/HDTCompatabilityWindow#8]
Hey stdscatchemall, you helped me out on Friday and I'm hoping you can assist me again. I've got things fully updated and the issue I'm having now is that the HDT Compatibility Window isn't displaying Hearthstone, but is instead displaying the main screen of the HDT:

![hdtcw](https://cloud.githubusercontent.com/assets/7796133/9472189/bd17a802-4b21-11e5-8dcf-52fb79a73df1.png)

I should add that it doesn't matter what the active window is, this is what is being broadcast by XSplit.

Thoughts?

**Comment by Assmodius** [comment]
Update - now I'm broadcasting a green screen with the deck overlay present. In the previous thread you'd mentioned that I needed to "Chroma Key it away" or something like that. I've played with the Color settings but I'm coming up empty. What do I do?

**Comment by stdscatchemall** [comment]
The window actually has to be open if you want to capture it. If you don't have the game open, the window won't show and xsplit selects the best window, in this case, the parent window of the overlay. Go to the plugin settings and disable the "Hide if HS is in background" option. Run the game, then Disable and Renable the scene. If possible, go back into the properties to make sure that the correct window is still selected.

**Comment by Assmodius** [comment]
Ok, messed with it some more and here's where I am:

![hdt issue](https://cloud.githubusercontent.com/assets/7796133/9475227/5fe8627c-4b33-11e5-8df9-138178f21ec6.jpg)

The bottom-left is an ipad that's looking at my twitch stream while the monitor shows what SHOULD be broadcast. It's almost where I need it to be but as you can see, the screen is all black on the stream. How do I rectify this?

**Comment by Assmodius** [comment]
There's something basic I must be missing here. This is what I'm experiencing: I have HS active with HDT running and showing my active deck on screen. I open XSplit Broadcaster, select "HDT Compatibiliity Window (DX9Ex)" (small typo in the window name there) and this is what I'm shown in XSplit:

![hdtcw](https://cloud.githubusercontent.com/assets/7796133/9475614/c41292ca-4b35-11e5-8632-001c57073f5f.png)

Then, while typing this out, XSplit updated to show me this:

![hdtcw2](https://cloud.githubusercontent.com/assets/7796133/9475627/e0ccf504-4b35-11e5-847d-41f804e283b1.png)

I have no idea why that occurred, There's something basic I'm missing or not doing, but it's frustrating and I'm lost. Hopefully I've given you enough information that you can see what I'm not seeing.

**Comment by stdscatchemall** [comment]
Because the HDT Compatibility Window is open, it showed up in xsplit. Otherwise, it matched it by executable name and read the original window (The same thing happens when you don't use my plugin).

At this point in the setup, this is where you chroma key the green out of the window. Chroma Key removes color of similarity based on your choice. If you don't know how to chroma key, i'm sure there is some instructions on the X-Split forums

**Comment by stdscatchemall** [comment]
Closed due to inactivity.
